### ISSUE TITLE
AttributeError: 'GradientBoostingClassifier' object has no attribute '_loss'

### ISSUE THREAD

**Issue by UK-codder** [VaibhavBichave/Phishing-URL-Detection#4]
when I run the code it shows like this on the web page... is it because of the version issue...

![image](https://user-images.githubusercontent.com/71163797/223712940-4edf49fa-0d34-4867-ad5a-0aecdc24f5cd.png)

I use python version 3.11.2

**Comment by TAMILSELVAM-A** [comment]
> when I run the code it shows like this on the web page... is it because of the version issue...
> 
> ![image](https://user-images.githubusercontent.com/71163797/223712940-4edf49fa-0d34-4867-ad5a-0aecdc24f5cd.png)
> 
> I use python version 3.11.2




HOW CAN I SOLVE THIS ERROR??

**Comment by vaibhavbichave** [comment]
This is because of your version issue, try to install python 3.9 and then follow steps written in readme.md to install dependant libraries.
