### ISSUE TITLE
> when I run the code it shows like this on the web page... is it because of the version issue...

### ISSUE THREAD

**Issue by TAMILSELVAM-A** [VaibhavBichave/Phishing-URL-Detection#5]
> when I run the code it shows like this on the web page... is it because of the version issue...
> 
> ![image](https://user-images.githubusercontent.com/71163797/223712940-4edf49fa-0d34-4867-ad5a-0aecdc24f5cd.png)
> 
> I use python version 3.11.2

HOW CAN I SOLVE THIS ERROR??

_Originally posted by @TAMILSELVAM-A in https://github.com/VaibhavBichave/Phishing-URL-Detection/issues/4#issuecomment-1510843459_

**Comment by pavanl1122** [comment]
how to resolve this issue?

**Comment by TAMILSELVAM-A** [comment]
> how to resolve this issue?

change the import statement of the model before dump that model...

{
from xgboost import XGBClassifier (##CHNAG THIS IMPORT SATEMENT INTO THIS)
gbc = GradientBoostingClassifier(max_depth=4,learning_rate=0.7)
gbc.fit(X_train,y_train)
}

{
from sklearn.ensemble import GradientBoostingClassifier (IMPORT THIS FILE )
gbc = GradientBoostingClassifier(max_depth=4,learning_rate=0.7)
gbc.fit(X_train,y_train)
}
